apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-etl-ai
  namespace: brightchecks
  labels:
    app: em-etl-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-etl-ai
  template:
    metadata:
      labels:
        app: em-etl-ai
    spec:
      containers:
      - name: em-etl-ai
        image: emindsguardians/em-etl-ai:M5
        command: ["python3.11","main.py"]
        ports: 
        - containerPort: 8005
---
apiVersion: v1
kind: Service
metadata:
  name: em-etl-ai
  namespace: brightchecks
spec:
  type: NodePort
  selector:
    app: em-etl-ai
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
      nodePort: 30087
