apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-etl-backend
  namespace: brightchecks
  labels:
    app: em-etl-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-etl-backend
  template:
    metadata:
      labels:
        app: em-etl-backend
    spec:
      containers:
      - name: em-etl-backend
        image: emindsguardians/em-etl-backend:M3
        command: ["sh","entrypoint.sh"]
        ports: 
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: em-etl-backend
  namespace: brightchecks
spec:
  type: NodePort
  selector:
    app: em-etl-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30083
