apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-etl-communication
  namespace: brightchecks
  labels:
    app: em-etl-communication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-etl-communication
  template:
    metadata:
      labels:
        app: em-etl-communication
    spec:
      containers:
      - name: em-etl-communication
        image: emindsguardians/em-etl-communication-service:b1
        command: ["npm","start"]
        ports: 
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: em-etl-communication
  namespace: brightchecks
spec:
  type: NodePort
  selector:
    app: em-etl-communication
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      nodePort: 30082
