apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-etl-data
  namespace: brightchecks
  labels:
    app: em-etl-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-etl-data
  template:
    metadata:
      labels:
        app: em-etl-data
    spec:
      containers:
      - name: em-etl-data
        image: emindsguardians/em-etl-data:V1
        command: ["sh","/em-etl-data/batch/controller/entrypoint.sh"]
        ports: 
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: em-etl-data
  namespace: brightchecks
spec:
  type: NodePort
  selector:
    app: em-etl-data
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
      nodePort: 30084
