apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-etl-gateway
  namespace: brightchecks
  labels:
    app: em-etl-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-etl-gateway
  template:
    metadata:
      labels:
        app: em-etl-gateway
    spec:
      containers:
      - name: em-etl-gateway
        image: emindsguardians/em-etl-gateway:M1
        command: ["npm","run","dev"]
        ports: 
        - containerPort: 8989
---
apiVersion: v1
kind: Service
metadata:
  name: em-etl-gateway
  namespace: brightchecks
spec:
  type: NodePort
  selector:
    app: em-etl-gateway
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989
      nodePort: 30085
