apiVersion: apps/v1
kind: Deployment
metadata:
  name: em-etl-iam
  namespace: brightchecks
  labels:
    app: em-etl-iam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: em-etl-iam
  template:
    metadata:
      labels:
        app: em-etl-iam
    spec:
      containers:
      - name: em-etl-iam
        image: emindsguardians/em-etl-iam:M8
        command: ["npm", "run", "dev"]
        ports: 
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: em-etl-iam
  namespace: brightchecks
spec:
  type: NodePort
  selector:
    app: em-etl-iam
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30088
